---
- hosts: all
  become: true
  vars_files:
    - vars/default.yml

  tasks:
    - name: Install prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

    - name: Install required system packages
      apt: name={{ sys_packages }} state=latest

    - name: set swap_file variable
      set_fact:
        swap_file: /swapfile

    - name: check if swap file exists
      stat:
        path: "{{ swap_file }}"
      register: swap_file_check

    - name: create swap file
      command: fallocate -l 1G {{ swap_file }}
      when: not swap_file_check.stat.exists

    - name: set permissions on swap file
      file:
        path: "{{ swap_file }}"
        mode: 0600

    - name: mkswap
      command: mkswap {{ swap_file }}
      when: not swap_file_check.stat.exists

    - name: swapon
      command: swapon {{ swap_file }}
      when: not swap_file_check.stat.exists

    - name: add to fstab
      lineinfile:
        dest: /etc/fstab
        regexp: "{{ swap_file }}"
        line: "{{ swap_file }} none swap sw 0 0"
      when: not swap_file_check.stat.exists

    - name: Ensure the locale exists
      locale_gen:
        name: en_US.UTF-8
        state: present
    - name: set as default locale
      command: localectl set-locale LANG=en_US.UTF-8
    - name: update local as en_US
      command: update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8

    - name: Install mosh
      apt: name=mosh state=present force_apt_get=yes

    - name: Install docker requirements
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        pkg:
          - docker-ce
          - docker-compose
        state: latest
        update_cache: true
